# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# follow next example
# ghcr.io/tavor118sn/gobot:v1.2.0-bba02e0-amd64
replicaCount: 1
image:
  registry: "ghcr.io"
  repository: "tavor118sn/gobot"
  tag: "v1.2.0-edd59ec"
  os: linux
  arch: amd64
secret:
  name: "gobot"
  env: "TELE_TOKEN"
  key: "token"
securityContext:
  privileged: true
